use_frameworks!

target 'AutomaticLayoutConstraint_Example' do
  pod 'AutomaticLayoutConstraint', :path => '../'

  target 'AutomaticLayoutConstraint_Tests' do
    inherit! :search_paths

    
  end
end
